version: '2'
services:
  postgres:
    image: postgres
    env_file:
      - back-tier.env
    networks:
      - back-tier
  web:
    build: ./hackmd/
    env_file:
      - front-tier.env
    volumes:
      - ./hackmd/config.json:/hackmd/config.json
      - ./hackmd/.sequelizerc:/hackmd/.sequelizerc
    links:
      - postgres
    expose:
      - "3000"
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
    external:
      name: nginx_default
  back-tier:
    driver: bridge
