version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - /srv/docker-state/hackmd/postgres/data/:/var/lib/postgresql/data/
    env_file:
      - back-tier.env
    networks:
      - back-tier
  web:
#    build: ./hackmd/
    image: hackmdio/hackmd:0.5.1
    command: /hackmd/docker-entrypoint.sh
    env_file:
      - front-tier.env
    volumes:
      - ./hackmd/config.json:/hackmd/config.json
      - ./hackmd/.sequelizerc:/hackmd/.sequelizerc
      - /srv/docker-state/hackmd/web/uploads/:/hackmd/public/uploads/
    links:
      - postgres
    expose:
      - "3000"
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
    external:
      name: nginx_default
  back-tier:
    driver: bridge
